<Project>
  <PropertyGroup>
    <Version>0.2.1</Version>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <Authors>YD359Team</Authors>
    <Company>YD359Team</Company>
    <Product>ZeppelinForms</Product>
    <PackageProjectUrl>https://github.com/YD359Team/ZeppelinForms-solution</PackageProjectUrl>
    <RepositoryUrl>https://github.com/YD359Team/ZeppelinForms-solution</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageIcon>ZF_medium.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>